version: '3'

services:
    redis:
        image: redis:3.2.10-alpine
    fpm:
        image: "elifesciences/journal:${IMAGE_TAG}"
        volumes:
            - ./parameters.yml:/srv/journal/app/config/parameters.yml
            - ./var/logs:/srv/journal/var/logs
        ports:
            - "9000:9000"
        env_file:
            - ./containers.env
        restart: always
        volumes:
            - ./parameters.yml:/srv/journal/app/config/parameters.yml
        depends_on:
            - redis
    # plan:
    # 1. serve only assets from this, with a custom nginx configuration
    # 2. route only /assets and /bundles to this from the real nginx
    # 3. route the rest to fpm:9000
    #assets:
    #    image: "elifesciences/journal_web:${IMAGE_TAG}"
    #    #volumes:
    #    #    - ./
    #    ports: 
    #        - "8080:8080"

