parameters:
    {% for name, value in pillar.journal.items() %}
    {{ name }}: {{ value }}
    {% endfor %}

    trusted_hosts: ['^.*elifesciences\.org$', 'localhost']
    trusted_proxies:
        - 192.0.0.1

    mailer_transport: smtp
    mailer_username: {{ pillar.journal.postfix_ses_mail.user }}
    mailer_password: {{ pillar.journal.postfix_ses_mail.pass }}
    mailer_host: {{ pillar.journal.postfix_ses_mail.smtp }}
    mailer_port: {{ pillar.journal.postfix_ses_mail.port }}
