parameters:
    {% for name, value in pillar.journal.items() %}
    {{ name }}: {{ value }}
    {% endfor %}

    trusted_hosts: ['^.*elifesciences\.org$', 'localhost']
    trusted_proxies:
        - 192.0.0.1

    mailer_transport: smtp
    mailer_host: {{ pillar.journal.mailer.host }}
    mailer_port: {{ pillar.journal.mailer.port }}
    mailer_username: {{ pillar.journal.mailer.username }}
    mailer_password: {{ pillar.journal.mailer.password }}
    mailer_encryption: {{ pillar.journal.mailer.encryption }}
