version: '3'

services:
    redis:
        image: redis:3.2.10-alpine
    fpm:
        image: "elifesciences/journal:${IMAGE_TAG}"
        volumes:
            - ./parameters.yml:/srv/journal/app/config/parameters.yml
            - ./var/logs:/srv/journal/var/logs
        ports:
            - "9000:9000"
        env_file:
            - ./containers.env
        restart: always
        volumes:
            - ./parameters.yml:/srv/journal/app/config/parameters.yml
        depends_on:
            - redis
    assets:
        build:
            context: .
            dockerfile: Dockerfile.web
            args:
                image_tag: ${IMAGE_TAG}
        image: "elifesciences/journal_web:${IMAGE_TAG}"
        volumes:
            - ./nginx-assets.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:8080"

