parameters:
    {% for name in ['secret', 'api_key', 'api_url', 'api_url_public', 'side_by_side_view_url', 'session_name' ] %}
    {{ name }}: '{{ pillar.journal.get(name) }}'
    {% endfor %}
    status_checks: {{ pillar.journal.get(name) }}

    trusted_hosts: ['^(.+\.)?elifesciences.org$', 'localhost', '^10\.[0-9]+\.[0-9]+\.[0-9]+$']

    redis_cache: redis://localhost

    mailer_transport: smtp
    mailer_host: {{ pillar.journal.mailer.host }}
    mailer_port: {{ pillar.journal.mailer.port }}
    mailer_username: {{ pillar.journal.mailer.username }}
    mailer_password: {{ pillar.journal.mailer.password }}
    mailer_encryption: {{ pillar.journal.mailer.encryption }}

    crm_url: https://crm.elifesciences.org/crm/civicrm/

    disqus_domain: elifesciences-staging

    # defaults for URL generation - host
    {% if pillar.journal.get('default_host') %}
    router.request_context.host: {{ pillar.journal.get('default_host') }}
    {% elif salt['elife.only_on_aws']() %}
    router.request_context.host: {{ salt['elife.cfg']('project.full_hostname') }}
    {% else %}
    router.request_context.host: dev--journal.elifesciences.org 
    {% endif %}
    
    # defaults for URL generation - scheme
    {% if salt['elife.only_on_aws']() %}
    router.request_context.scheme: https
    {% else %}
    router.request_context.scheme: http
    {% endif %}
