parameters:
    secret: unused
    api_key: public
    api_url: http://localhost:8081
    api_url_public: http://localhost:8081
    side_by_side_view_url: http://lens.localdomain
    session_name: {{ pillar.journal.session_name }}_local
    status_checks: {{ pillar.journal.status_checks }}
    gtm_id: null
    disqus_domain: elifesciences-staging
    redis_cache: null

    trusted_hosts: localhost

    mailer_transport: smtp
    mailer_host: localhost
    mailer_port: 25
    mailer_username: anonymous
    mailer_password: ""
    mailer_encryption: null

    crm_url: ''

    router.request_context.host: localhost
    router.request_context.http_port: 8080
    router.request_context.scheme: http
