{% set standard_keys = ['secret', 'api_key', 'api_url', 'api_url_public', 'side_by_side_view_url', 'session_name', 'status_checks', 'submit_url', 'submit_url_redirects', 'gtm_id', 'google_optimize_id', 'cb_id', 'oauth2_client_id', 'oauth2_client_secret', 'hypothesis_api', 'hypothesis_authority', 'hypothesis_client_id', 'hypothesis_client_secret', 'xpub_client_id', 'xpub_client_secret', 'feature_xpub', 'submission_client_id', 'submission_client_secret', 'cache_control', 'era_articles', 'rds_articles', 'subject_rewrites', 'calls_to_action']  %}

parameters:
    {% if pillar.journal.get('redis_cache') == false %}
    redis_cache: null
    {% elif salt['elife.cfg']('cfn.outputs.ElastiCacheHost1') %}
    redis_cache: {{ "redis://" + salt['elife.cfg']('cfn.outputs.ElastiCacheHost1') + ":" + salt['elife.cfg']('cfn.outputs.ElastiCachePort1') }}
    {% else %}
    {% do standard_keys.extend(['redis_cache']) %}
    {% endif %}

    {% if pillar.journal.get('redis_sessions') == false %}
    redis_sessions: null
    {% elif salt['elife.cfg']('cfn.outputs.ElastiCacheHost2') %}
    redis_sessions: {{ "redis://" + salt['elife.cfg']('cfn.outputs.ElastiCacheHost2') + ":" + salt['elife.cfg']('cfn.outputs.ElastiCachePort2') }}
    {% else %}
    {% do standard_keys.extend(['redis_sessions']) %}
    {% endif %}

    {% for name in standard_keys %}
    {{ name }}:
        {{ pillar.journal.get(name)|json }}
    {% endfor %}

    dismissible_info_bars: {{ pillar.journal.dismissible_info_bars }}

    trusted_hosts:
        - '^(.+\.)?{{ pillar.elife.domain }}$'
        - 'localhost'
        - '^10\.[0-9]+\.[0-9]+\.[0-9]+$'
        - '^172\.(16|17|18|19|2[0-9]|30|31)\.[0-9]+\.[0-9]+$'
        - '^192.168\.[0-9]+\.[0-9]+$'

    mailer_transport: smtp
    mailer_host: {{ pillar.journal.mailer.host }}
    mailer_port: {{ pillar.journal.mailer.port }}
    mailer_username: {{ pillar.journal.mailer.username }}
    mailer_password: {{ pillar.journal.mailer.password }}
    mailer_encryption: {{ pillar.journal.mailer.encryption }}

    crm_url: https://crm.elifesciences.org/crm/civicrm/

    # defaults for URL generation - host
    {% if pillar.journal.get('default_host') %}
    router.request_context.host: {{ pillar.journal.get('default_host') }}
    {% elif salt['elife.only_on_aws']() %}
    router.request_context.host: {{ salt['elife.cfg']('project.full_hostname') }}
    {% else %}
    router.request_context.host: dev--journal.{{ pillar.elife.domain }} 
    {% endif %}
    
    # defaults for URL generation - scheme
    {% if salt['elife.only_on_aws']() %}
    router.request_context.scheme: https
    {% else %}
    router.request_context.scheme: http
    {% endif %}
