parameters:
    secret: SomethingSecret
    api_key: public
    api_url: http://localhost:8081
    api_url_public: http://localhost:8081
    side_by_side_view_url: http://localhost:8080/_lens/
    session_name: {{ pillar.journal.session_name }}_local
    status_checks: 
        API Dummy: ping
    gtm_id: ~
    disqus_domain: elifesciences-staging
    # deprecated
    redis: ~
    # end of deprecated
    redis_cache: ~
    redis_sessions: ~

    # port should only be open where allowed anyway
    trusted_hosts: ['localhost', '{{ pillar.elife.env }}--journal.{{ pillar.elife.domain }}']

    oauth2_client_id: journal-local-demo
    oauth2_client_secret: fakesecret

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: ~
    mailer_username: ~
    mailer_password: ~
    mailer_encryption: ~

    crm_url: http://localhost:8080/_crm/

    router.request_context.host: localhost
    router.request_context.http_port: 8080
    router.request_context.scheme: http

    hypothesis_api: https://hypothes.is/api/
    hypothesis_authority: some-authority
    hypothesis_client_id: some-id
    hypothesis_client_secret: ThisIsASecret
