{% set on_elasticache = salt['elife.cfg']('cfn.outputs.ElastiCacheHost') %}
{% set standard_keys = ['secret', 'api_key', 'api_url', 'api_url_public', 'side_by_side_view_url', 'session_name', 'status_checks', 'gtm_id', 'disqus_domain', 'oauth2_client_id', 'oauth2_client_secret']  %}

parameters:
    {% if pillar.journal.get('redis') == false %}
    redis: null
    {% elif on_elasticache %}
    {% set remote_redis = "redis://" + salt['elife.cfg']('cfn.outputs.ElastiCacheHost') + ":" + salt['elife.cfg']('cfn.outputs.ElastiCachePort') %}
    redis: {{ remote_redis }}
    {% else %}
    {% do standard_keys.extend(['redis']) %}
    {% endif %}

    {% for name in standard_keys %}
    {% set value = pillar.journal.get(name, 'null') %}
    {% if value == '' %}
    {{ name }}: ''
    {% elif value is not none %}
    {{ name }}: {{ value }}
    {% else %}
    {{ name }}: null
    {% endif %}
    {% endfor %}

    trusted_hosts: ['^(.+\.)?{{ pillar.elife.domain }}$', 'localhost', '^10\.[0-9]+\.[0-9]+\.[0-9]+$', '^172\.(16|17|18|19|2[0-9]|30|31)\.[0-9]+\.[0-9]+$', '^192.168\.[0-9]+\.[0-9]+$']

    mailer_transport: smtp
    mailer_host: {{ pillar.journal.mailer.host }}
    mailer_port: {{ pillar.journal.mailer.port }}
    mailer_username: {{ pillar.journal.mailer.username }}
    mailer_password: {{ pillar.journal.mailer.password }}
    mailer_encryption: {{ pillar.journal.mailer.encryption }}

    crm_url: https://crm.elifesciences.org/crm/civicrm/

    # defaults for URL generation - host
    {% if pillar.journal.get('default_host') %}
    router.request_context.host: {{ pillar.journal.get('default_host') }}
    {% elif salt['elife.only_on_aws']() %}
    router.request_context.host: {{ salt['elife.cfg']('project.full_hostname') }}
    {% else %}
    router.request_context.host: dev--journal.{{ pillar.elife.domain }} 
    {% endif %}
    
    # defaults for URL generation - scheme
    {% if salt['elife.only_on_aws']() %}
    router.request_context.scheme: https
    {% else %}
    router.request_context.scheme: http
    {% endif %}
