parameters:
    secret: unused
    api_key: unused
    api_url: http://localhost:8080
    api_url_public: http://localhost:8080
    side_by_side_view_url: http://lens.localdomain
    session_name: {{ pillar.journal.session_name }}
    status_checks: {{ pillar.journal.status_checks }}
    gtm_id: ''
    disqus_domain: elifesciences_staging
    redis_cache: ''

    trusted_hosts: '*'

    mailer_transport: smtp
    mailer_host: localhost
    mailer_port: 25
    mailer_username: anonymous
    mailer_password: ""
    mailer_encryption: null

    crm_url: ''

    # defaults for URL generation - host
    router.request_context.host: localhost:8081
    router.request_context.scheme: http
