parameters:
    {% for name, value in pillar.journal.items() %}
    {{ name }}: {{ value }}
    {% endfor %}

    trusted_hosts: ['^.*elifesciences\.org$', 'localhost']
    trusted_proxies:
        - 192.0.0.1

