imports:
  - behat.yml.dist

default:
    extensions:
        Behat\MinkExtension:
            base_url: http://{{ pillar.elife.env }}--journal.elifesciences.org/
        Behat\Symfony2Extension:
            kernel:
                env: {{ pillar.elife.env }}
